---
title: Energy infrastructure as built environment in rural rangelands
author: DA McGranahan
output: 
  html_document:
    highlight: tango
---

```{r setup, echo=FALSE, warning=FALSE, message = FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE, 
                      echo=FALSE, eval=TRUE)
pacman::p_load(tidyverse, cowplot, patchwork, wesanderson)
  BuGnPal = c( "#67A9CF" ,"#3690C0" ,"#02818A", "#016450")
  FFgrad = wes_palette("FantasticFox1")[c(3,2,4,5)]
# load data 
  load('./data/NoPlainsEnergy.Rdata')
```

```{r region_map}
footprint <- 
    bind_rows(
      NoPlainsEnergy$TurbineFootprint %>%
        select( ) %>%
        mutate(type = 'Wind farm'), 
      NoPlainsEnergy$WellFootprint %>%
         select( ) %>%
        mutate(type = 'Petroleum basin') ) %>% 
    st_simplify(dTolerance = 500)
  
np_us <-
  ggplot() + theme_void() + 
  geom_sf(data = us, fill = 'grey90', color = NA) +
  geom_sf(data =  np %>% st_union( ),
          fill = 'lightblue', color = NA)  + 
  geom_sf(data = us, 
          size = 0.15, 
          fill = NA, color = 'grey60') 
np_footprints <-
  ggplot() + theme_void() +
  geom_sf(data = np, fill = NA) +
  geom_sf(data = footprint, aes(fill = type, color = type)) +
  scale_color_manual("Energy type", values = wes_palette('Zissou1')[c(2,5)]) +
  scale_fill_manual("Energy type", values = wes_palette('Zissou1')[c(1,5)])


v1<-viewport(width = 1, height = 1, x = 0.5, y = 0.5) #  main map
v2<-viewport(width = 0.3, height = 0.3, x = 0.7, y = 0.2) # inset map
print(np_footprints,vp=v1) 
print(np_us,vp=v2)

```

