---
title: Soil Heating effects of prescribed fire in US Great Plains
author: "Devan Allen McGranahan"
output:
  word_document:
    reference_docx: arial_template.docx
csl: SpringerNature.csl
bibliography: SoilheatingBib.bib
---
  
```{r setup, include=FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = FALSE, eval = FALSE)
# pacman::p_load(tidyverse, pander)
```

Soil is a natural system comprised of minerals, organic matter, air, and water. 
Soil development begins with the weathering of local geologic parent material and is continually influenced by climate and organisms. 
Soil is not just the natural medium for plant growth---it is the habitat for organisms that regulate the delivery of multiple ecosystem services, and a substantial repository for elements and minerals important to global processes, such as carbon and nitrogen. 

Many soil properties can be affected by wildland fire, either directly or indirectly. 
Variability in these affects comes largely from the intensity and duration of heat exposure as well as the environmental conditions before and after fire [@mcgranahan2021; @pereira2019]. 
Direct effects are those produced by exposure to heat generated by combustion---e.g., chemical conversion of organic nitrogen to mineral ammonium, protein denaturation. 
Indirect effects are responses that follow environmental alterations attributable to fire---e.g., biomass removal, increased insolation, and second-order vegetation dynamics.

## General patterns of soil heating

There is little evidence that prescribed fire has substantial impact on biotic or abiotic soil properties in the Great Plains. 
The overall lack of effect is primarily due to the fact that soil heating in grassland ecosystems is relatively benign, due to the low residence time of flame fronts in fuelbeds dominated by fine fuels, especially under the moderate fire weather conditions typical of prescribed fire in the region. 
Soil itself resists heating---the majority of heat released from surface combustion rises, and organic matter and air effectively insulate against energy from moving downward. 
Research from Europe indicates that only under conditions of very high soil moisture and prolonged heat input will substantial heating penetrate more than 3-5 cm into the soil profile and subsequently affect soil properties [@giovannini1997; @valette1994; @barreiro2020]. 
The limited data on soil heating during prescribed fire in the Great Plains provides evidence of this drastic attenuation (Table 1).

Table 1: Selection of studies reporting soil surface and/or sub-surface temperatures from prescribed fire in Great Plains grassland communities. 
All reported data collected from thermocouples connected to digital dataloggers.
Sensor placement refers to where the hot end of thermocouple was placed; negative values indicate depth below soil surface. 
* Values derived via soil heating model. 

Study	         | Prairie type (Location)       |Sensor placement | Temperature ($^\circ$C)
---------------|-------------------------------|-----------------|------------------------
@archibold2003 | Fescue prairie (Saskatchewan) | −1 cm	         | 22
@archibold1998 | Mixed grass (Saskatchewan)    | Soil surface    | 252
		           |                               | −5 cm	         | 12
@zopfi2020     | Mixed grass (central North Dakota) | Soil surface | 150
@zopfi2020     | Mixed grass (sw North Dakota) | Soil surface | 120
@mcgranahan2022| Mixed grass (sw North Dakota)    | Soil surface    | 275
               |                               | −2 cm *         | 100 *
               |                               | −5 cm *         | 50 *
@ohrtman2015   | Tallgrass (South Dakota)      | Soil surface	   | 384
@anderson2016  | Tallgrass (Texas)             | −5 cm           | 28


Many fire effects on soils are modulated by the fire regime, particularly the frequency and intensity of fire. 
While infrequent fire can increase nitrogen availability and increase nutrient cycling rates, annual burning increased soil respiration in tallgrass prairie [@johnson2001]. 
Indeed, annual burning might generally elevate the net export of necessary nutrients above what deposition and mineralization can replace [@brye2006]. 
Conversely, low-intensity fires in *Poa pratensis*-dominated mixed grass prairie in North Dakota had no appreciable effect on soil properties [@gerhard2022]. 
The conclusion here was that soil properties are resilient to heating, but given that soil surface temperatures in the studied burned units averaged just 150$^\circ$C [@zopfi2020], it is just as likely that the soil strata measured received very little heating. 

## Specific belowground responses to soil heating

Prescribed fire tends to increase soil surface temperature and decrease soil moisture, but the magnitude of reported effects are generally small. 
In western Oklahoma, soil temperatures were 1-3$^\circ$C higher after burns, but soil moisture on these sandy soils did not vary among treatments [@vermeire2005]. 
In eastern Montana, burned plots were 0.5$^\circ$C warmer and 1% drier than unburned plots [@vermeire2011]. 
In southern Saskatchewan, soil moisture did not vary signficantly between burned and unburned sites while in only one instance was a 5$^\circ$C increase in soil temperature significantly greater than in unburned controls [@yang2013]. 
But drier soil might not be a universal response to fire, especially in grazed areas: @spiess2021 reported *higher* soil moisture in burned patches in which grazers maintained low-stature vegetation, suggesting reducing the amount of leaf tissue capable of moving soil moisture into the atmosphere might conserve water in the soil. 
This hypothesis, however, has yet to be formally tested at the plant level, although altered water flux has been documented in burned prairie [@fischer2012]. 

Plant-available, or *mineralized*, nitrogen (N) has been widely reported to increase in response to fire. 
Although much of this research has been conducted beyond the Great Plains [@mcgranahan2021], work from our region corroborates these trends. 
In one of few studies to directly measure mineral N and soil heating, @mcgranahan2022 found that ammonium levels increased immediately after fall fire in North Dakota, and nitrate levels were elevated 7 mo after fire, into the next growing season (Fig. 1).
This same pattern was reported in Colorado shortgrass steppe [@augustine2014].
Similarly, @reinhart2016 also reported increases in soil N following fire in eastern Montana. 

Soil microbes have generally been described as resilient to fire---in the event that limited reductions in microbial biomass occur immediately after fire, abundance typically recovers within weeks or months [@mcgranahan2022]. 
But fire-driven reductions are not universally observed [@reinhart2016] and microbial community composition is typically unaffected by fire [@dangi2010; @spiess2021; @mcgranahan2022]. 

Most reported fire effects on soil properties are limited to upper soil layers. 
For example, in mesquite-prairie rangeland in Texas, @dai2006 found fire regimes that included summer fires increased soil organic C and total N in the top 20 cm, but had no effect on either variable lower in the profile. 
Thus, the role of fire in long-term, ecosystem-level soil nutrient dynamics, such as carbon sequestration, in the Great Plains likely lies mostly in indirect effects related to plant community composition---e.g., herbaceous vs. woody vegetation---than direct effects of fire. 
In some systems, *pyrogenic* charcoal byproducts of wildland fire known as *PyC* or *PyOM* have been shown to decompose more slowly than similar amounts of carbon or organic matter unaltered by heating, suggesting a recalcitrance that might contribute to carbon sequestration [@quilliam2013]. 
However, experimental work on grass tissue, specifically, reports similar rates of microbial activity [@hilscher2009; @hilscher2011], suggesting carbonization does little to enhance the carbon storage capacity of the dominant vegetation type in the Great Plains.


# References